Jobportal/Jobportal/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hr/',include("hr.urls")),
    path('jobseeker/',include("jobseeker.urls"))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Jobportal/hr/urls.py
from django.urls import path
from hr import views
urlpatterns = [
    path('signin/',views.LoginView.as_view(),name="signin"),
    path('index/',views.DashboardView.as_view(),name="index"),
    path('signout/',views.SignoutView.as_view(),name = "signout"),
    path('addcategory/',views.AddcategoryView.as_view(),name = "category"),
    path('category/<int:pk>',views.CategoryremoveView.as_view(),name = "del_category"),
    path('jobadd/',views.AddjobView.as_view(),name = "addjob"),
    path('jobdel/<int:pk>',views.DeljobView.as_view(),name='jobdel'),
    path('joblist/',views.JoblistView.as_view(),name='joblist'),
    path('jobedit/<int:pk>',views.JobupdateView.as_view(),name='edit'),
    path('jobdetails/<int:pk>',views.JobdetailsView.as_view(),name='details'),
]
    

Jobportal/hr/models.py
from django.db import models

# Create your models here.

Jobportal/myapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=20,unique = True)

    def __str__(self):
        return self.name


class Job(models.Model):
    title = models.CharField(max_length=200)
    company_name = models.CharField(max_length=200)
    experience = models.PositiveIntegerField()
    salary = models.PositiveIntegerField()
    qualification = models.CharField(max_length=200)
    skills = models.CharField(max_length =200)
    contact = models.PositiveBigIntegerField(null = True)
    poster = models.ImageField(upload_to="poster",null=True)
    category = models.ForeignKey(Category,on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.title
    
class Student(models.Model):
    age = models.PositiveIntegerField()
    options = (
        ('male','male'),('female','female'),('others','others')
    )
    gender = models.CharField(max_length =20 ,choices =options,default ="male")
    address = models.CharField(max_length = 200)
    contact = models.IntegerField(null = True)
    email = models.EmailField()
    qualification = models.CharField(max_length = 200)
    skills = models.CharField(max_length =200)
    experience = models.PositiveIntegerField()
    resume = models.FileField(upload_to="files",null=True)
    user = models.OneToOneField(User,on_delete = models.DO_NOTHING,null = True,related_name = "profile")

    def __str__(self):
        return self.name
    
class Applications(models.Model):
    jobs = models.ForeignKey(Job,on_delete = models.DO_NOTHING)
    student = models.ForeignKey(User,on_delete = models.DO_NOTHING)
    options = (
        ("pending","pending"),("rejected","rejected"),("processing","processing")
    )

    status = models.CharField(max_length = 30, choices =options, default = "pending")

Jobportal/hr/forms.py
from django import forms
from myapp.models import Category,Job
from django.forms import Select

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ["name"]

class JobForm(forms.ModelForm):
    class Meta:
        model = Job
        # exclude = ('salary')
        fields = '__all__'
        widgets = {
            'category':Select(attrs={
                'class': "form-select",
                
                
                }),
        }

Jobportal/hr/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login,logout
from django.urls import reverse_lazy

from django.views.generic import View,FormView,TemplateView,CreateView,ListView,DeleteView,UpdateView,DetailView  # A view for displaying a form and rendering a template response
from hr.forms import LoginForm,JobForm,CategoryForm
from myapp.models import Job,Category

class LoginView(FormView):
    template_name = "login.html"
    form_class = LoginForm

    def post(self,request,*args,**kwargs):
        form = LoginForm(request.POST)
        if form.is_valid():
            u_name = form.cleaned_data.get("username")
            pwd = form.cleaned_data.get("password")
            user_obj = authenticate(request,username=u_name,password=pwd)
            if user_obj:
                login(request,user_obj)
                if request.user.is_superuser:
            
                    return redirect ("index")
                else:
                    return redirect("seekerindex")
            else:
                print("failed")
            return render(request,"login.html",{"form":form})    
        
class DashboardView(TemplateView):
    template_name = "index.html"


class SignoutView(View):
    def get(self,request,*args,**kwargs):
        logout(request)
        return redirect("signin")
    
class AddcategoryView(CreateView,ListView):
    template_name = "category.html"
    form_class = CategoryForm
    success_url = reverse_lazy("category")
    context_object_name="data"
    model = Category


class CategoryremoveView(View):
    def get(self,request,*args,**kwargs):
        id=kwargs.get("pk")
        Category.objects.get(id=id).delete()
        return redirect("category")
    




class AddjobView(CreateView):
    template_name = "add_job.html"
    form_class = JobForm
    model = Job
    success_url = reverse_lazy("joblist")
    context_object_name = ("qs")


class DeljobView(View):
    def get(self,request,*args,**kwargs):
        id = kwargs.get("pk")
        Job.objects.get(id=id).delete()
        return redirect("joblist")


class JoblistView(ListView):
    template_name = "job_list.html"
    model = Job
    context_object_name = "jobs"

class JobupdateView(UpdateView):
    template_name ="jobupdate.html"
    form_class = JobForm
    model = Job
    success_url = reverse_lazy('joblist')

class JobdetailsView(View):
    def get(self,request,*args,**kwargs):
        id = kwargs.get("pk")
        qs = Job.objects.filter(id=id)
        return render(request,"jobdetails.html",{"qs":qs})
        

    

Jobportal/hr/templates/add_job.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Jobs</title>

    <link rel="stylesheet" href="style.css">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</head>

<body class="overflow-x-hidden bg-secondary ">
{%if form.errors%}
{{form.errors}}
{%endif%}

    <!-- {%block body_block%} -->

    <div class="container d-flex justify-content-around">
        <form action="" method="post" class="bg-white w-75 rounded-3" enctype="multipart/form-data">
            {% csrf_token %}
            <p class="fw-bold fs-4 ">Add Job</p>
            <hr class="mb-1 w-25 border-4">
            <div class=" row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-12 "><label for="">Title :</label><input type="text"
                        name="title" class="form-control"></div>
                <div class="col-lg-6 col-md-6 col-sm-12 col-12 mt-4 "><label for="id_category">Category :</label>
                    <!-- <select class="form-control" name="category" id=""> -->
                        <!-- for loop -->
                        <!-- <option value="{{form.category}}">{{form.name}}</option> -->
                        <!-- for loop -->
                    <!-- </select> -->
                    {{form.category}}
                </div>
                <div class="col-lg-6 col-md-6 col-sm-12 col-12 mt-4"><label class="" for="">Company
                        :</label><input type="text" name="company_name" class="form-control"></div>
                <div class="col-lg-6 col-md-6 col-sm-12 col-12 mt-4"><label class="" for="">Experience
                        :</label><input type="text" name="experience" class="form-control"></div>
                <div class="col-lg-6 col-md-6 col-sm-12 col-12 mt-4"><label class="" for="">Salary
                        :</label><input type="text" name="salary" class="form-control"></div>
                <div class="col-lg-6 col-md-6 col-sm-12 col-12 mt-4"><label class="" for="">Skills
                        :</label><input type="text" name="skills" class="form-control"></div>

                <div class="col-lg-6 col-md-6 col-sm-12 col-12 mt-4"><label class="" for="">Poster
                        :</label><input type="file" name="poster" class="form-control"></div>

                <div class="col-lg-6 col-md-6 col-sm-12 col-12 mt-4"><label class="" for="">Contact :</label><input
                        type="number" name="contact" class="form-control"></div>
                <div class="col-lg-6 col-md-6 col-sm-12 col-12 mt-4"><label class="" for="">Qualification
                        :</label><input type="text" name="qualification" class="form-control"></div>
                <!-- <div class="col-lg-6 col-md-6 col-sm-12 col-12 mt-4"><label class="" for="">Last Date :</label><input
                        type="date" name="last_date" class="form-control"></div> -->
                <!-- <div class="col-lg-6 col-md-6 col-sm-12 col-12 mt-4"><label class="" for="">Description
                        :</label><textarea class="form-control" name="description"></textarea></div> -->

                
               
                <div class="text-center">
                    <button class="btn btn-dark mt-4 mb-4 w-50">Add Job</button>
                    <br>
                </div>


            </div>
        </form>
    </div>



    <!-- {%endblock%} -->


</body>

</html>

Jobportal/hr/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Jobs</title>

    <link rel="stylesheet" href="style.css">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</head>

<body class="overflow-x-hidden">

<!-- {%block body_block%} -->

    <div class="">
        <div class="row ">
            <div class="col-2 px-5 pt-5 bg-dark vh-100" id="sticky-sidebar">
                <div class="sticky-top">
                    <div class="nav flex-column">
                        <p class="fw-bold fs-4 text-center text-light">Admin / User</p>
                        <hr class="text-light">
                        <a href="http://127.0.0.1:8000/hr/index"
                            class="text-light text-decoration-none mt-4 p-2 fs-6 btn btn-dark text-start">Home</a>
                        <a href="http://127.0.0.1:8000/hr/addcategory/"
                            class="text-light text-decoration-none p-2 fs-6 btn btn-dark text-start">Category</a>
                        <!-- <a href="http://127.0.0.1:8000/hr/addjob/"
                            class="text-light text-decoration-none p-2 fs-6 btn btn-dark text-start">Jobs</a> -->
                            <div class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                  Jobs
                                </button>
                                <ul class="dropdown-menu">
                                  <li><a class="dropdown-item" href="{% url 'joblist' %}">Job List</a></li>
                                  <li><a class="dropdown-item" href="http://127.0.0.1:8000/hr/jobadd/">Addjob</a></li>
                                  <li><a class="dropdown-item" href="#">More</a></li>
                                </ul>
                              </div>    
                        <a href="#"
                            class="text-light text-decoration-none p-2 fs-6 btn btn-dark text-start">Applications</a>
                    </div>
                </div>
            </div>
            <div class="col mx-2 " id="main">
                <div class="mt-5"></div>
                <h3 class="fw-bold">Hello {{request.user}},</h3>
                <br><br>
                
                    <br><br>
               
                {%block mainblock%}
                
                {%endblock%}

            </div>
        </div>
    </div>

    <!-- {%endblock%} -->


</body>

</html>
</body>
</html>

Jobportal/hr/templates/category.html
{%extends 'base.html'%}

{%block mainblock%}

<div class="row mt-5">
    <div class="col-2"></div>
    <div class="col-8">
        <form action="" method="post">
            {%csrf_token%}
        <h1>Category</h1>
            <hr class="mb-5 w-25 border-4">
            <div class="d-flex mt-4">
                <input type="text" name="name" class="form-control ">
                <button type="submit" class="btn btn-dark ms-2">Add</button>
            </div>
        </form>
        <table class="table table-bordered mt-4">
            <thead class="table-dark ">
                <tr>
                    <th>Jobs</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody class="text-center">
                {%for d in data%}
              <tr>
                    <td>{{d.name}}</td>
                    <td><a href="{%url 'del_category' d.id %}"><i class="fa-solid fa-trash"></i></a></td>
              </tr>
                {%endfor%}
            </tbody>
        </table>
    </div>
    <div class="col-2"></div>
</div>
{%endblock%}

Jobportal/hr/templates/index.html
{% extends "base.html" %}
{% block mainblock %}
<div class="d-flex justify-content-evenly">
    <a href="{% url 'category'  %}" class="btn btn-dark w-25">Category</a>
    <a href="{% url 'addjob'  %}" class="btn btn-dark w-25">Jobs</a>
    
    <a href="#" class="btn btn-dark w-25">Applications</a>
</div>
{% endblock %}

Jobportal/hr/templates/job_list.html
{% extends "base.html" %}
{%block mainblock%}
{% for i in jobs %}
<div class="card mb-3 w-75 ">
    <div class="row g-0">
      <div class="col-md-4">
        {%if 'i.poster' %}
        <img src="{{ i.poster.url }}" class="img-fluid rounded-start" alt="...">
        {%endif%}  
    </div>
      <div class="col-md-5">
        <div class="card-body">
            

          <h5 class="card-title">{{i.title}}</h5>
          <h5 class="card-title">{{i.company_name}}</h5>
          <!-- <h5 class="card-title">{{i.experience}}</h5> -->
          <!-- <h5 class="card-title">{{i.salary}}</h5>
          <h5 class="card-title">{{i.qualification}}</h5>
          <h5 class="card-title">{{i.skills}}</h5> -->
          <h5 class="card-title">{{i.category}}</h5>

          <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
        </div>
      </div>
      <div class="col-md-3">
        <a href="{% url 'details' i.id %}"><button class="btn btn-dark mt-4 mb-4 w-50">VIEW</button></a>
        <a href="{% url 'jobdel' i.id %}"><button class="btn btn-dark mt-4 mb-4 w-50">DELETE</button></a>
        <a href="{% url 'edit' i.id %}"><button class="btn btn-dark mt-4 mb-4 w-50">UPDATE</button></a>
      </div>
    </div>
  </div>
{%endfor%}
{%endblock%}

Jobportal/hr/templates/jobdetails.html
{% extends "base.html" %}
{%block mainblock%}
{% for i in qs %}
<div class="card mb-3 w-75 ">
    <div class="row g-0">
      <div class="col-md-4">
        {%if 'i.poster' %}
        <img src="{{ i.poster.url }}" class="img-fluid rounded-start" alt="...">
        {%endif%}  
    </div>
      <div class="col-md-5">
        <div class="card-body">
          
            

          <h5 class="card-title">{{i.title}}</h5>
          <h5 class="card-title">{{i.company_name}}</h5>
          <h5 class="card-title">{{i.experience}}</h5>
          <h5 class="card-title">{{i.salary}}</h5>
          <h5 class="card-title">{{i.qualification}}</h5>
          <h5 class="card-title">{{i.skills}}</h5> 
          <h5 class="card-title">{{i.category}}</h5>
          

          <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
        </div>
      </div>
      <div class="col-md-3">
        <!-- <a href=""><button class="btn btn-dark mt-4 mb-4 w-50">view</button></a> -->
        <a href="{% url 'jobdel' i.id %}"><button class="btn btn-dark mt-4 mb-4 w-50">DELETE</button></a>
        <a href="{% url 'edit' i.id %}"><button class="btn btn-dark mt-4 mb-4 w-50">UPDATE</button></a>
      </div>
    </div>
  </div>
  {% endfor %}
{%endblock%}

Jobportal/hr/templates/jobupdate.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Jobs</title>

    <link rel="stylesheet" href="style.css">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</head>

<body class="overflow-x-hidden bg-secondary ">
{%if form.errors%}
{{form.errors}}
{%endif%}

    <!-- {%block body_block%} -->

    <div class="container d-flex justify-content-around">
        <form action="" method="post" class="bg-white w-75 rounded-3" enctype="multipart/form-data">
            {% csrf_token %}
            <p class="fw-bold fs-4 ">UPDATE JOB</p>
            <hr class="mb-1 w-25 border-4">
            <div class=" row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-12 "><label for="">Title :</label><input type="text"
                     value="{{form.title.value}}"   name="title" class="form-control"></div>
                <div class="col-lg-6 col-md-6 col-sm-12 col-12 mt-4"><label for="">Category :</label>
                    <select class="form-control"  value="{{form.category.value}}" name="category" id="">
                        <!-- for loop -->
                        <option value="{{form.category}}">{{form.name}}</option>
                        <!-- for loop -->
                    </select>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-12 col-12 mt-4"><label class="" for="">Company
                        :</label><input type="text"  value="{{form.company_name.value}}" name="company_name" class="form-control"></div>
                <div class="col-lg-6 col-md-6 col-sm-12 col-12 mt-4"><label class="" for="">Experience
                        :</label><input type="text"  value="{{form.experience.value}}" name="experience" class="form-control"></div>
                <div class="col-lg-6 col-md-6 col-sm-12 col-12 mt-4"><label class="" for="">Salary
                        :</label><input type="text"  value="{{form.salary.value}}" name="salary" class="form-control"></div>
                <div class="col-lg-6 col-md-6 col-sm-12 col-12 mt-4"><label class="" for="">Skills
                        :</label><input type="text"  value="{{form.skills.value}}" name="skills" class="form-control"></div>

                <div class="col-lg-6 col-md-6 col-sm-12 col-12 mt-4"><label class="" for="">Poster
                        :</label><input type="file" name="poster" class="form-control">{{form.poster}}</div>

                <div class="col-lg-6 col-md-6 col-sm-12 col-12 mt-4"><label class="" for="">Contact :</label><input
                        type="number"  value="{{form.contact.value}}" name="contact" class="form-control"></div>
                <div class="col-lg-6 col-md-6 col-sm-12 col-12 mt-4"><label class="" for="">Qualification
                        :</label><input type="text"  value="{{form.qualification.value}}" name="qualification" class="form-control"></div>
                <!-- <div class="col-lg-6 col-md-6 col-sm-12 col-12 mt-4"><label class="" for="">Last Date :</label><input
                        type="date" name="last_date" class="form-control"></div> -->
                <!-- <div class="col-lg-6 col-md-6 col-sm-12 col-12 mt-4"><label class="" for="">Description
                        :</label><textarea class="form-control" name="description"></textarea></div> -->

                
               
                <div class="text-center">
                    <button class="btn btn-dark mt-4 mb-4 w-50">UPDATE JOB</button>
                    <br>
                </div>


            </div>
        </form>
    </div>



    <!-- {%endblock%} -->


</body>

</html>

Jobportal/hr/templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Jobs</title>

    <link rel="stylesheet" href="style.css">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</head>

<body class="overflow-x-hidden bg-secondary">



    <div class="container d-flex justify-content-around">
        <form action="" method="post" class="bg-white m-5 p-5 w-50 rounded-3">
            {%csrf_token%}
            <p class="fw-bold fs-4 "> Login</p>
            <hr class="mb-5 w-25 border-4">
            <div class="text-center">
                <input type="text" class="form-control  text-center" name="username" placeholder="enter username"><br>
                <input type="text" class="form-control  text-center" name="password" placeholder="Password"><br>

                <button type="submit" class="btn btn-dark w-50 mt-5 mb-5">Login</button>
                <br>
                <p>Or<br>Create an Account</p>
                <a href="#" class="btn btn-outline-dark w-25">Register</a>
            </div>
        </form>
    </div>

  


</body>

</html>